apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: instvote
  source:
    path: prod
    repoURL: https://github.com/voa2000/argo.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true